/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package itngs_mvc.view;

import java.awt.Color;
import java.io.File;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 * @author juliana
 */
public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
        jTFile1.setEditable(false);
        jTFile1.setBackground(Color.white);
        jTFile2.setEditable(false);
        jTFile2.setBackground(Color.white);
        jPanelGraphic.setVisible(false);
        jPanelVectorRemove.setVisible(false);
        jTPQualityClean.setEnabledAt(1, false);
        jTPQualityClean.setEnabledAt(2, false);
        jlProgress.setText("        ");
        jlProgressPercent.setText("   ");
        jlSituationProgress.setText("   ");
        jProgressBarQuality.setStringPainted(true);
        jRBAllCharts.setSelected(true);
        makeMegaBlastParameters();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroupDevice = new javax.swing.ButtonGroup();
        buttonGroupPaired = new javax.swing.ButtonGroup();
        buttonGroupCharts = new javax.swing.ButtonGroup();
        jBCancel = new javax.swing.JButton();
        jBFile1 = new javax.swing.JButton();
        jBFile2 = new javax.swing.JButton();
        jBGenerateGraphics = new javax.swing.JButton();
        jBStart = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jBCancelRemove = new javax.swing.JButton();
        jBStartRemove = new javax.swing.JButton();
        jCBMinComplex = new javax.swing.JComboBox();
        jCBMinQual = new javax.swing.JComboBox();
        jCBTrimBegin = new javax.swing.JComboBox();
        jCBTrimEnd = new javax.swing.JComboBox();
        jCBCostGap = new javax.swing.JComboBox();
        jCBCostGapExt = new javax.swing.JComboBox();
        jCBExpectValue = new javax.swing.JComboBox();
        jCBIdentityCut = new javax.swing.JComboBox();
        jCBMinScore = new javax.swing.JComboBox();
        jCBNumProc = new javax.swing.JComboBox();
        jCBPointMatche = new javax.swing.JComboBox();
        jCBPenalty = new javax.swing.JComboBox();
        jCBWordSize = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        //jLabel11 = new javax.swing.JLabel();
        jlProgress = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlProgressPercent = new javax.swing.JLabel();
        jlSituationProgress = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelGraphic = new javax.swing.JPanel();
        jPanelVectorRemove = new javax.swing.JPanel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBarQuality = new JProgressBar();
        jRB454 = new javax.swing.JRadioButton();
        jRBIllumina = new javax.swing.JRadioButton();
        jRBSolexa = new javax.swing.JRadioButton();
        jRBSanger = new javax.swing.JRadioButton();
        jRBPairedEnd = new javax.swing.JRadioButton();
        jRBSingleEnd = new javax.swing.JRadioButton();
        jRBAllCharts = new javax.swing.JRadioButton();
        jRBQualCharts = new javax.swing.JRadioButton();
        jRBVectorCharts = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jTFile1 = new javax.swing.JTextField();
        jTFile2 = new javax.swing.JTextField();
        jTPQualityClean = new javax.swing.JTabbedPane();
        jTFileClean = new javax.swing.JTextField();
        jTFileClean2 = new javax.swing.JTextField();
        jTFVectorSeq = new javax.swing.JTextField();
        jTFOutputFile = new javax.swing.JTextField();
        jBFinish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TISNG - Tratamento Inicial de sequências de nova geração");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(getIconImages());
        setLocationByPlatform(true);
        setResizable(false);

        jTPQualityClean.setRequestFocusEnabled(false);
//        jTPQualityClean.addComponentListener(new java.awt.event.ComponentAdapter() {
//            public void componentHidden(java.awt.event.ComponentEvent evt) {
//                jTPQualityCleanComponentHidden(evt);
//            }
//        });

        jLabel1.setText("Arquivo 1");

        jLabel2.setText("Arquivo 2");

        buttonGroupPaired.add(jRBPairedEnd);
        jRBPairedEnd.setText("Paired-end");
        jRBPairedEnd.setEnabled(false);
        jRBPairedEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPairedEndActionPerformed(evt);
            }
        });

        buttonGroupPaired.add(jRBSingleEnd);
        jRBSingleEnd.setText("Single-end");
        jRBSingleEnd.setEnabled(false);
        jRBSingleEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSingleEndActionPerformed(evt);
            }
        });

        jLabel3.setText("Metodologia de sequenciamento:");

        jTFile1.setText("Caminho do arquivo...");
        jTFile1.setEnabled(false);

        jTFile2.setText("Caminho do arquivo...");
        jTFile2.setEnabled(false);

        jBFile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jBFile1.setText("Pesquisa");
        jBFile1.setEnabled(false);
        jBFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFile1ActionPerformed(evt);
            }
        });

        jBFile2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jBFile2.setText("Pesquisa");
        jBFile2.setEnabled(false);
        jBFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFile2ActionPerformed(evt);
            }
        });

        jCBMinComplex.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));
        jCBMinComplex.setEnabled(false);

        jLabel4.setText("Nota minima de qualidade");

        jLabel5.setText("Minimo para complexidade");

        jCBMinQual.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));
        jCBMinQual.setEnabled(false);
        jCBMinQual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBMinQualActionPerformed(evt);
            }
        });

        jLabel6.setText("Posição inicial de corte");

        jLabel7.setText("Posição final de corte");

        jBStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.png"))); // NOI18N
        jBStart.setText("Iniciar");
        jBStart.setEnabled(false);

        jBCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jBCancel.setText("Cancelar");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        jCBTrimBegin.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));
        jCBTrimBegin.setEnabled(false);
        jCBTrimBegin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTrimBeginActionPerformed(evt);
            }
        });

        jCBTrimEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));
        jCBTrimEnd.setEnabled(false);

        jLabel13.setText("Sequenciador");

        buttonGroupDevice.add(jRBIllumina);
        jRBIllumina.setText("Illumina");
        jRBIllumina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBIlluminaActionPerformed(evt);
            }
        });

        buttonGroupDevice.add(jRBSolexa);
        jRBSolexa.setText("Solexa");
        jRBSolexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSolexaActionPerformed(evt);
            }
        });

        buttonGroupDevice.add(jRBSanger);
        jRBSanger.setText("Sanger");
        jRBSanger.setName("FASTQ_SANGER"); // NOI18N
        jRBSanger.setOpaque(true);
        jRBSanger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSangerActionPerformed(evt);
            }
        });

        jLabel14.setText("Selecione arquivos para limpeza");

        buttonGroupDevice.add(jRB454);
        jRB454.setText("Roche 454");
        jRB454.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB454ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jSeparator1)
                .addComponent(jSeparator7)
                .addComponent(jSeparator2)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel3)
                                        .addGap(89, 89, 89)
                                        .addComponent(jRBSingleEnd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRBPairedEnd)
                                        .addGap(41, 41, 41))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jBFile2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jBFile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(26, 26, 26))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jRBIllumina)
                                                        .addGap(79, 79, 79)
                                                        .addComponent(jRB454)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jRBSanger)
                                                        .addGap(109, 109, 109)
                                                        .addComponent(jRBSolexa)
                                                        .addGap(100, 100, 100))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addGap(11, 11, 11)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel7)
                                                                .addComponent(jLabel6))
                                                        .addGap(75, 75, 75)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jCBTrimBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jCBTrimEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(49, 49, 49)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel4)
                                                                        .addGap(30, 30, 30))
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                                        .addGap(87, 87, 87)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jCBMinQual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jCBMinComplex, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(0, 24, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jBCancel)
                                                        .addGap(17, 17, 17)
                                                        .addComponent(jBStart)))
                                        .addGap(28, 28, 28))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jlProgress)
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jlSituationProgress)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jProgressBarQuality, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(28, 28, 28)
                                                                        .addComponent(jlProgressPercent))))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(9, 9, 9)
                                                        .addComponent(jLabel14)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRBSanger)
                                .addComponent(jRBIllumina)
                                .addComponent(jRBSolexa)
                                .addComponent(jRB454))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRBPairedEnd, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRBSingleEnd))
                                .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1)
                                                .addComponent(jTFile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jBFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2)
                                                .addComponent(jTFile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jBFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jCBMinQual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jCBMinComplex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel5)
                                                        .addGap(10, 10, 10))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(173, 173, 173)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel6)
                                                .addComponent(jCBTrimBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCBTrimEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBStart, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlProgress)
                                .addComponent(jProgressBarQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlProgressPercent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlSituationProgress)
                        .addGap(24, 24, 24))
        );

        jTPQualityClean.addTab("Limpeza de qualidade", jPanel1);

        jTFileClean.setText("Caminho do arquivo...");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jButton6.setText("Pesquisa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTFVectorSeq.setText("Caminho do arquivo...");

        jLabel9.setText("Sequência do vetor");

        jCheckBox1.setText("Use sequências UniVec");

        jBCancelRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jBCancelRemove.setText("Cancelar");
        jBCancelRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelRemoveActionPerformed(evt);
            }
        });

        jBStartRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/done.png"))); // NOI18N
        jBStartRemove.setText("Iniciar");

        //jLabel11.setText("*Path default is /home/user/Documents/Clean/outputClean.fasta");

        jTFileClean2.setText("Caminho do arquivo...");

        jLabel10.setText("Arquivo limpo");

        jCBExpectValue.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));

        jLabel15.setText("Parâmetros MegaBLAST");

        jCBCostGap.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));

        jLabel16.setText("Custo para abrir gap");

        jLabel17.setText("Valor esperado");

        jLabel19.setText("Custo para extender gap");

        jCBCostGapExt.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));

        jCBPointMatche.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));

        jLabel20.setText("Ponto por matche");

        jCBNumProc.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));

        jLabel21.setText("Qtde. de processadores");

        jLabel22.setText("Tamanho de palavra");

        jCBWordSize.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));

        jLabel23.setText("Score mínimo a exibir");

        jCBMinScore.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));

        jCBIdentityCut.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));

        jLabel24.setText("Percentual de identidade de corte");

        jLabel25.setText("Penalidade para um mismatch");

        jCBPenalty.setModel(new javax.swing.DefaultComboBoxModel(new String[]{}));

        javax.swing.GroupLayout jPanelVectorRemoveLayout = new javax.swing.GroupLayout(jPanelVectorRemove);
        jPanelVectorRemove.setLayout(jPanelVectorRemoveLayout);
        jPanelVectorRemoveLayout.setHorizontalGroup(
                jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator5)
                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVectorRemoveLayout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCheckBox1)
                                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTFVectorSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6))
                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFileClean, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFileClean2))
                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        //.addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBCancelRemove)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBStartRemove))
                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(jSeparator8))
                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel19)
                                                .addComponent(jLabel20))
                                        .addGap(97, 97, 97)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                                        .addComponent(jCBCostGapExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(72, 72, 72)
                                                        .addComponent(jLabel23)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jCBMinScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                                        .addComponent(jCBPointMatche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(72, 72, 72)
                                                        .addComponent(jLabel24)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jCBIdentityCut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jCBCostGap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jCBExpectValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(72, 72, 72)
                                                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                                                        .addComponent(jLabel21)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                                                        .addComponent(jCBNumProc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                                                        .addComponent(jLabel22)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jCBWordSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap())
                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(jCBPenalty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel15)
                                .addContainerGap(563, Short.MAX_VALUE)))
        );
        jPanelVectorRemoveLayout.setVerticalGroup(
                jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTFileClean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFileClean2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCBNumProc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCBExpectValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCBCostGap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jCBWordSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCBCostGapExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jCBMinScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCBPointMatche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jCBIdentityCut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCBPenalty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel9)
                                                .addComponent(jTFVectorSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addComponent(jCheckBox1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                //.addComponent(jLabel11)
                                .addComponent(jBCancelRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBStartRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                .addGroup(jPanelVectorRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelVectorRemoveLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(482, Short.MAX_VALUE)))
        );

        jTPQualityClean.addTab("Remoção do vetor", jPanelVectorRemove);

        //jTPQualityClean.addTab("Remoção do vetor", jPanelVectorRemove);

        jLabel18.setText("Gráficos de limpeza");

        buttonGroupCharts.add(jRBAllCharts);
        jRBAllCharts.setText("Todos");

        buttonGroupCharts.add(jRBQualCharts);
        jRBQualCharts.setText("Limpeza de qualidade");

        buttonGroupCharts.add(jRBVectorCharts);
        jRBVectorCharts.setText("Remoção do vetor");

        jBGenerateGraphics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/graphics.png"))); // NOI18N
        jBGenerateGraphics.setText("Gerar gráfico");
        jBGenerateGraphics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerateGraphicsActionPerformed(evt);
            }
        });

        jBFinish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        jBFinish.setText("Finalizar");
        jBFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGraphicLayout = new javax.swing.GroupLayout(jPanelGraphic);
        jPanelGraphic.setLayout(jPanelGraphicLayout);
        jPanelGraphicLayout.setHorizontalGroup(
                jPanelGraphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGraphicLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelGraphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelGraphicLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanelGraphicLayout.createSequentialGroup()
                                        .addComponent(jRBAllCharts)
                                        .addGap(54, 54, 54)
                                        .addComponent(jRBQualCharts)
                                        .addGap(49, 49, 49)
                                        .addComponent(jRBVectorCharts)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                                        .addComponent(jBGenerateGraphics)))
                        .addContainerGap())
                .addComponent(jSeparator6)
                .addComponent(jBFinish)
        );
        jPanelGraphicLayout.setVerticalGroup(
                jPanelGraphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelGraphicLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelGraphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRBAllCharts)
                                .addComponent(jRBQualCharts)
                                .addComponent(jRBVectorCharts)
                                .addComponent(jBGenerateGraphics))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(427, Short.MAX_VALUE)
                        .addComponent(jBFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTPQualityClean.addTab("Gráficos", jPanelGraphic);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTPQualityClean)
                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTPQualityClean, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jRBSingleEndActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jTFile1.setEnabled(true);
        jBFile1.setEnabled(true);
        jTFile2.setEnabled(false);
        jTFile2.setText("");
        jBFile2.setEnabled(false);

    }

    private void jRBPairedEndActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jTFile2.setEnabled(true);
        jBFile2.setEnabled(true);
        //jCBMinComplex.setEnabled(true);
    }

    private void jBFile1ActionPerformed(java.awt.event.ActionEvent evt) {

        File file;
        JFileChooser fc = new JFileChooser(jTFile1.getText());
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int result = fc.showOpenDialog(null);

        if (result == JFileChooser.CANCEL_OPTION) {
            jTFile1.setText("");
            //boolean t = fileIsNull(file.getAbsolutePath());
        } else {
            file = fc.getSelectedFile();
            String f = file.getAbsolutePath();
            if (isFastq(file.getAbsolutePath()) && fileIsNull(file.getAbsolutePath())) {
                jTFile1.setText(file.getAbsolutePath());
                jTFile1.setEditable(false);
                if (jRBSingleEnd.isSelected()) {
                    activeQualityParameters(true);
                }
            }
        }

    }

    private void jBFile2ActionPerformed(java.awt.event.ActionEvent evt) {
        File file;
        JFileChooser fc = new JFileChooser(jTFile2.getText());
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int result = fc.showOpenDialog(null);

        if (result == JFileChooser.CANCEL_OPTION) {
            jTFile2.setText("");
        } else {
            file = fc.getSelectedFile();
            jTFile2.setText(file.getAbsolutePath());
            jTFile2.setEditable(false);
            if (jTFile1.getText().equals("")) {
                activeQualityParameters(false);
            } else {
                activeQualityParameters(true);
            }
        }
    }

    private void jRBSangerActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        activePairedEndButtons();
        jCBMinQual.removeAllItems();
        for (int i = 0; i <= 93; i++) {
            jCBMinQual.addItem(i);
        }
        makeTrimCombo(500 / 2);
    }

    private void jRBIlluminaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        activePairedEndButtons();
        jCBMinQual.removeAllItems();
        for (int i = -5; i <= 62; i++) {
            jCBMinQual.addItem(i);
        }

        makeTrimCombo(100 / 2);
    }

    private void jRBSolexaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        activePairedEndButtons();
        jCBMinQual.removeAllItems();
        for (int i = 0; i <= 62; i++) {
            jCBMinQual.addItem(i);
        }
        makeTrimCombo(100 / 2);
    }

    private void jCBMinQualActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jBStart.setEnabled(true);
        jCBMinComplex.removeAllItems();

        for (double i = 0; i <= 10; i++) {
            jCBMinComplex.addItem(i / 10);
        }
    }

    private void jCBTrimBeginActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jBGenerateGraphicsActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void jRB454ActionPerformed(java.awt.event.ActionEvent evt) {
        activePairedEndButtons();
        jCBMinQual.removeAllItems();
        for (int i = 0; i <= 40; i++) {
            jCBMinQual.addItem(i);
        }
        makeTrimCombo(400 / 2);
    }

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void jBCancelRemoveActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void jBFinishActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        jTFVectorSeq.setEditable(false);
        File file;
        JFileChooser fc = new JFileChooser(jTFVectorSeq.getText());
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int result = fc.showOpenDialog(null);

        if (result == JFileChooser.CANCEL_OPTION) {
            jTFVectorSeq.setText("");
        } else {
            file = fc.getSelectedFile();
            jTFVectorSeq.setText(file.getAbsolutePath());
            jTFVectorSeq.setEditable(false);
        }
    }
//    private void jButton6ActionPerformed(ActionEvent evt) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * @param args the command line arguments
     */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
    private void activePairedEndButtons() {
        jRBSingleEnd.setEnabled(true);
        jRBPairedEnd.setEnabled(true);
        jRBSingleEnd.setSelected(true);
        jTFile1.setEnabled(true);
        jBFile1.setEnabled(true);
        jCBMinComplex.setEnabled(true);
    }

    /**
     * Ativa ou desativa parametros de limpeza
     *
     * @param b true para ativos, false para inativos
     */
    private void activeQualityParameters(boolean b) {
        jCBMinQual.setEnabled(b);
        jCBMinQual.setEnabled(b);
        jCBMinComplex.setEnabled(b);
        jCBTrimBegin.setEnabled(b);
        jCBTrimEnd.setEnabled(b);
    }

    /**
     * Load the combobox of cut value, with the mean length of the sequences of
     * sequencing
     *
     * @param limit commom length registred of writers
     */
    private void makeTrimCombo(int limit) {
        jCBTrimBegin.setEnabled(true);
        jCBTrimBegin.removeAllItems();
        for (int i = 0; i <= limit; i++) {
            jCBTrimBegin.addItem(i);
        }

        jCBTrimEnd.setEnabled(true);
        jCBTrimEnd.removeAllItems();
        jCBTrimEnd.addItem(0);
        for (int i = 1; i <= limit; i++) {
            jCBTrimEnd.addItem(i);
        }
    }

    public void makeMegaBlastParameters() {
        for (int i = 0; i < 10000; i++) {
            jCBExpectValue.addItem(i);
        }
        jCBExpectValue.setSelectedIndex(10);

        for (int i = -1; i < 2; i++) {
            jCBCostGap.addItem(i + "    ");
        }

        for (int i = -1; i < 2; i++) {
            jCBCostGapExt.addItem(i + "    ");
        }

        for (int i = 1; i < 3; i++) {
            jCBPointMatche.addItem(i + "     ");
        }

        for (int i = -3; i < 3; i++) {
            jCBPenalty.addItem(i + "   ");
        }

        for (int i = 1; i <= 12; i++) {
            jCBNumProc.addItem(i + "   ");
        }
        jCBNumProc.setSelectedIndex(0);

        for (int i = 4; i < 40; i += 4) {
            jCBWordSize.addItem(i + "   ");
        }
        jCBWordSize.setSelectedIndex(6);

        for (int i = 0; i <= 50; i++) {
            jCBMinScore.addItem(i + "   ");
        }

        for (int i = 0; i <= 100; i++) {
            jCBIdentityCut.addItem(i + "   ");
        }

    }

    /**
     * Check if file is a FASTQ
     *
     * @param file file path
     * @return true or false
     */
    private boolean isFastq(String file) {
        int end = file.length();

        boolean fastq = false;
        if (file.substring(end - 5, end).contains("fastq")) {
            fastq = true;
            return fastq;
        } else {
            JOptionPane.showMessageDialog(null,
                    "Caminho de arquivo inválido! A extensão do arquivo deve ser .fastq",
                    //"Invalid file path! The file extension should be .fastq",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
        return fastq;
    }

    /**
     * Check of file path is ok
     *
     * @param filePath path file
     * @return true to ok
     */
    public static boolean fileIsNull(String filePath) {

        boolean path = false;

        if (filePath == null || filePath.isEmpty()) {

            JOptionPane.showMessageDialog(null,
                    "Caminho inválido!",
                    //"Invalid file path!",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);

        } else {

            path = true;

        }
        return path;
    }

    /**
     * Get a string of selected button of a group
     *
     * @param buttonGroup
     * @return name of button
     */
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }

    // Variables declaration - do not modify                     
    public javax.swing.ButtonGroup buttonGroupDevice;
    public javax.swing.ButtonGroup buttonGroupPaired;
    public javax.swing.ButtonGroup buttonGroupCharts;
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBFile1;
    private javax.swing.JButton jBFile2;
    public javax.swing.JButton jBGenerateGraphics;
    public javax.swing.JButton jBStart;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jBCancelRemove;
    public javax.swing.JButton jBStartRemove;
    //Parameters of quality clean
    public javax.swing.JComboBox jCBMinComplex;
    public javax.swing.JComboBox jCBMinQual;
    public javax.swing.JComboBox jCBTrimBegin;
    public javax.swing.JComboBox jCBTrimEnd;
    //Parameters Megablast
    public javax.swing.JComboBox jCBCostGap;
    public javax.swing.JComboBox jCBCostGapExt;
    public javax.swing.JComboBox jCBExpectValue;
    public javax.swing.JComboBox jCBIdentityCut;
    public javax.swing.JComboBox jCBMinScore;
    public javax.swing.JComboBox jCBNumProc;
    public javax.swing.JComboBox jCBPointMatche;
    public javax.swing.JComboBox jCBPenalty;
    public javax.swing.JComboBox jCBWordSize;
    public javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    //private javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jlProgress;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jlProgressPercent;
    public javax.swing.JLabel jlSituationProgress;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGraphic;
    public javax.swing.JPanel jPanelVectorRemove;
    public javax.swing.JProgressBar jProgressBar2;
    public javax.swing.JProgressBar jProgressBarQuality;
    //RadioButtons sequencing
    private javax.swing.JRadioButton jRB454;
    private javax.swing.JRadioButton jRBIllumina;
    private javax.swing.JRadioButton jRBSanger;
    private javax.swing.JRadioButton jRBSolexa;
    //RadioButtons Single or pair
    private javax.swing.JRadioButton jRBSingleEnd;
    private javax.swing.JRadioButton jRBPairedEnd;
    //Charts RadioButtons
    public javax.swing.JRadioButton jRBAllCharts;
    public javax.swing.JRadioButton jRBQualCharts;
    public javax.swing.JRadioButton jRBVectorCharts;

    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public javax.swing.JTextField jTFile1; //File path of FASTQ 1 (Screen 1)
    public javax.swing.JTextField jTFile2; //File path of FASTQ 2  (Screen 1)
    public javax.swing.JTabbedPane jTPQualityClean; //Tab of panel to clean Quality
    public javax.swing.JTextField jTFileClean; //Fasta file to alignment with the vector (Screen 2)
    public javax.swing.JTextField jTFileClean2; //Fasta file to alignment with the vector (Screen 2)
    public javax.swing.JTextField jTFVectorSeq; //Banco Univec ou sequencia do vetor (Screen 2)
    public javax.swing.JTextField jTFOutputFile; //Arquivo de saída (Tela 2)
    private javax.swing.JButton jBFinish;
    // End of variables declaration                   
}
